// pub use crate::adc::ChannelTimeSequence as _stm32_hal_adc_ChannelTimeSequence;
pub use crate::afio::AfioExt as _gd32_hal_afio_AfioExt;
// pub use crate::crc::CrcExt as _stm32_hal_crc_CrcExt;
pub use crate::dma::CircReadDma as _gd32_hal_dma_CircReadDma;
pub use crate::dma::DmaExt as _gd32_hal_dma_DmaExt;
pub use crate::dma::ReadDma as _stm32_hal_dma_ReadDma;
pub use crate::dma::ReadWriteDma as _gd32_hal_dma_ReadWriteDma;
pub use crate::dma::WriteDma as _gd32_hal_dma_WriteDma;
pub use crate::fmc::FMCExt as _gd32_hal_flash_FlashExt;
pub use crate::gpio::GpioExt as _gd32_hal_gpio_GpioExt;
pub use crate::hal::adc::OneShot as _embedded_hal_adc_OneShot;
pub use crate::hal::digital::v2::StatefulOutputPin as _embedded_hal_digital_StatefulOutputPin;
pub use crate::hal::digital::v2::ToggleableOutputPin as _embedded_hal_digital_ToggleableOutputPin;
pub use crate::hal::prelude::*;
pub use crate::rcu::RcuExt as _gd32_hal_rcu_RcuExt;
pub use crate::time::U32Ext as _gd32_hal_time_U32Ext;
pub use crate::timer::PwmExt as _gd32c1xx_hal_timer_PwmExt;
pub use crate::timer::SysTimerExt as _gd32c1xx_hal_timer_SysCounterExt;
pub use crate::timer::TimerExt as _gd32c1xx_hal_timer_TimerExt;
pub use fugit::ExtU32 as _fugit_ExtU32;
pub use fugit::RateExtU32 as _fugit_RateExtU32;
